baseurl = "/ifz/"
languageCode = "de"
defaultContentLanguage="de"
theme = "terminal"
paginate = 5
title = "Interface Zero"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.de]
    languageName = "Deutsch"
    title = "Interface Zero"
    subtitle = "Sammlung an Regeländerungen, Anpassungen und Hintergrundinfos"
    keywords = ""
    copyright = ""
    menuMore = "Mehr anzeigen"
    readMore = "Mehr lesen"
    readOtherPosts = "Andere Artikel lesen"

    [languages.de.params.logo]
      logoText = "Interface Zero"
      logoHomeLink = "/"

    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "showcase"
        name = "Wichtige Artikel"
        url = "/showcase"

